name: ui
description: UI for Retinopathy

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  url_launcher: ^5.7.10
  animated_text_kit: ^3.1.0
  firebase_core:
  firebase_storage: ^7.0.0
  firebase_auth: ^0.20.0+1
  cloud_firestore:
  modal_progress_hud: ^0.1.3
  curved_navigation_bar: ^0.3.7
  image_picker: ^0.6.7+21
  percent_indicator: "^2.1.7+2"
  bordered_text: ^1.0.1
  intl: ^0.16.1
  flutter_native_splash: ^0.1.4
  http: ^0.12.2
  dio: ^3.0.10
  speedometer: "^1.0.1"
  font_awesome_flutter: ^8.4.0
  flutter_hooks: ^0.16.0
  google_sign_in: ^4.5.9
  cached_network_image: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#42a5f5"

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf